### ISSUE TITLE
.bashrc snippet references the wrong filename

### ISSUE THREAD

**Issue by markmcd** [4z3/fzf-plugins#1]
The snippet tries to source `history.bash` but the file is `history-exec.bash`.

I would have just sent a PR for this but due to the use of WTFPL I can't (due to [company policy](https://opensource.google.com/docs/thirdparty/licenses/#wtfpl-not-allowed)) 🙄

**Comment by markmcd** [comment]
Oh and thanks for sharing this - very handy!

**Comment by 4z3** [comment]
Thanks for pointing out the issue, I've just fixed it!

**Comment by markmcd** [comment]
Thanks!

(And yeah, it's common, at least in tech, for employment contracts to include IP ownership. The license governs not just the code, but it's use as well. i.e. I can run this on my home computer if I choose, but I can't run it at work, and I can't make anything with it.)
