### ISSUE TITLE
zsh version

### ISSUE THREAD

**Issue by CaptainQuirk** [4z3/fzf-plugins#3]
Hi there !

Any plans to port this to zsh as well ?

Thanks in advance !

**Comment by 4z3** [comment]
I have no plans to port this myself at the moment as I'm not using zsh. You could try [@nhooyr's version](https://github.com/nhooyr/dotfiles/blob/92623b7a3e9fa421d191f6c2bb77de4ce60aa367/zsh/fzf.zsh#L48-L61) which was shared in https://github.com/junegunn/fzf/pull/1492#issuecomment-636445364, and there appears to be another version in https://github.com/junegunn/fzf/pull/2037.

That said, if there is a desire to add a zsh-version to this repository, then pull-requests are welcome :sunglasses:
