### ISSUE TITLE
"readline: maximum macro execution nesting level exceeded" in vi mode

### ISSUE THREAD

**Issue by tgdfool2** [4z3/fzf-plugins#5]
Hi All,

Since a couple of days (weeks?), I'm facing an issue with the `history-exec.bash` plugin while running Bash in vi mode (`set -o vi`).

On a freshly-installed Ubuntu 20.04, installed `fzf` and `fzf-plugins` as follow:
```
apt-get update && apt-get -y install vim git lsb-release curl wget
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
git clone https://github.com/4z3/fzf-plugins ~/.fzf-plugins
```

My `.bashrc` configuration looks as follow:
```
set -o vi

# Configure and enable fzf
export FZF_DEFAULT_COMMAND='fd --exclude Library/'
export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
export FZF_DEFAULT_OPTS="--layout=reverse --inline-info"
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Enable fzf plugins
FZF_CTRL_R_EDIT_KEY=ctrl-e
FZF_CTRL_R_EXEC_KEY=enter
source ~/.fzf-plugins/history-exec.bash
```

While pressing CTRL+R, this produces the following error:
```
root@f780ceb68dc8:/# ^X^Addi`__fzf_history__`^X^E^X^X^Addi`__fzf_history__`^X^E^X^X^Addi`__fzf_history__`^X^E^X^X^Addi`__fzf_history__`^X^E^X^X^Addi`__fzf_history__`^X^E^X^X^Addi`__fzf_history__`^X^E^X^X^Addi`__fzf_history__`^X^E^X^X^Addi`__fzf_history__`^X^E^X^X^Addi`__fzf_history__`^X^E^X^X^Addi`__fzf_history__`^X^E^X^X^Addi`__fzf_history__`^X^E^X^X^Addi`__fzf_history__`^X^E^X^X^Addi`__fzf_history__`^X^E^X^X^Addi`__fzf_history__`^X^E^X^X^Addi`__fzf_history__`^X^E^X^X^Addi`__fzf_history__`^X^E^X^X^Addi`__fzf_history__`^X^E^Xreadline: maximum macro execution nesting level exceeded
```

The same issue **cannot** be reproduced while using Bash in emacs mode.

Could you please help me to solve this issue?

Thanks in advance!

**Comment by 4z3** [comment]
Hi, looks like some previously existing) keybindings are missing nowadays.  I'm not using vi-mode myself so I don't know when or why this happened. Either way, after adding the missing keybindings it works as expected:
```shell
  bind '"\C-x\C-a": vi-movement-mode'
  bind '"\C-x\C-e": shell-expand-line'
  bind '"\C-x\C-r": redraw-current-line'
  bind '"\C-x^": history-expand-line'
```

**Comment by 4z3** [comment]
Looks like some previously existing keybindings got removed in vi-mode. I'm not using vi-mode myself so I wasn't aware these got removed, and I'm not sure when or why this happened. Either way, I've created https://github.com/4z3/fzf-plugins/pull/6 that maybe fixes the issue. @tgdfool2, can you please test if this works for you?

There might be a better way to fix this issue, but looking at `bind -P` it seems like most readline commands used in `history-exec.bash` aren't bound anymore.

**Comment by tgdfool2** [comment]
Hi @4z3,

Thank you very much for this quick fix! I did a small test right now and all the functionalities seem to work as expected again.

Just for my understanding: Are these bindings that have been removed from the default vi-mode Bash configuration that you were relying on for the fzf bindings?

Thanks again and have a nice day!

**Comment by tgdfool2** [comment]
Closing the issue. Feel free to merge https://github.com/4z3/fzf-plugins/pull/6.

**Comment by 4z3** [comment]
> Are these bindings that have been removed from the default vi-mode Bash configuration that you were relying on for the fzf bindings?

I cannot say that with 100% certainty that these bindings have been removed from the default vi-mode Bash configuration. It could also be a distribution thing. I haven't tried to figure out the cause of the removal. All I can really say is that these bindings were available in the past but are not now anymore, and that they never were part of any private configuration.

If I learn more about this topic in the future, I'll add references here.

_If anyone who's reading this comment at some point happens to knows when or were [these vi-mode bindings](https://github.com/4z3/fzf-plugins/pull/6/files) got removed, please feel free to add a comment here :)_
